### ISSUE TITLE
Stuck! Preso!

### ISSUE THREAD

**Issue by Diddle1** [FernandoHansen666/ScaryRF-315-433mhz#1]
Hey there, I'm close to getting this to work not sure if its my wiring or what not.. Anyway possible way you have discord or a way to help me understand the controls here? I would be interested in helping working on it if you wanted in some free time, i think a webserver would be another cool option seems most of my run better than way.

**Comment by FernandoHansen666** [comment]
Hello, my Discord is Scary Hollow#5095. My English isn't very good, but you can contact me through Discord, and I'll be happy to help.
