### ISSUE TITLE
If i have evilcrows

### ISSUE THREAD

**Issue by shanejohn15** [FernandoHansen666/ScaryRF-315-433mhz#2]
Evil crow rf v2 are 2x cc1101 chips with an esp32 and a usb for power and battery hookup.. so I was wondering is it possible to hook up the buttons and oled to this just as easy? And would It be easier for someone not with mini electronics solder experience to start off with the evil crow rf v2 and flash your firmware after getting the screen and buttons on?

**Comment by FernandoHansen666** [comment]
I believe not, since the Evilcrow firmware has significant differences. It might be easier to modify my project using some functions from Evilcrow than to adapt a screen and buttons directly onto Evilcrow itself.

**Comment by FernandoHansen666** [comment]
I'm adding a new SD card module and considering using another CC1101. But now I need to buy more CC1101s and redo the board. In the future, when I have the money for it, I'll order everything from PCBWay to make it easier.
