### ISSUE TITLE
randomness

### ISSUE THREAD

**Issue by banned747** [FernandoHansen666/ScaryRF-315-433mhz#3]
Hey man, love this code, well done. I cannot get it to work. I have setup as you said, but when I turn it on I get the home screen, then if I click a button it shows a graph which reads nothing, if I click another button I get "signal received 300mhz" but it's the same everytime without any signals close. 

Please also label each button in your wiring diagram. As what they do I.e home, capture etc. 

Thank you!!

**Comment by banned747** [comment]
i got it working using another gpio pin. must be a conflict for some reaosn on my esp32d. all buttons work except for the main one to capture a signal. i am reading signals fine but it is not caputring anything. ive seen a video of your device and using button linked to gpio14 i am still getting nothing.

**Comment by FernandoHansen666** [comment]
The 300mhz detection happens to me when the antenna has bad contact, regarding signal reading, there are some controls that the library does not yet recognize to store the capture, so in the future I will add a RAW capture function so as not to need to recognize the control
